name: Build & Deploy Spring Boot

on:
  push:
    branches:
      - master  # Runs when code is pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Set Environment Variables
        run: |
          echo "DB_EMPLOYEE_URL=${{ secrets.DB_EMPLOYEE_URL }}" >> $GITHUB_ENV
          echo "DB_EMPLOYEE_USER=${{ secrets.DB_EMPLOYEE_USER }}" >> $GITHUB_ENV
          echo "DB_EMPLOYEE_PASS=${{ secrets.DB_EMPLOYEE_PASS }}" >> $GITHUB_ENV

      - name: Run Spring Boot Application (Optional)
        run: mvn spring-boot:run
